version: '3.1'

services:

  postgres-db:
    image: postgres:12.1-alpine
    # restart: always (?)
    environment:
    - POSTGRES_PASSWORD=cbe_password
    - POSTGRES_USER=cbe_user
    - POSTGRES_DB=cbe_images
    ports:
    - 5432:5432

  elasticsearch-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    environment: 
    - discovery.type=single-node
    ports:
    - 9200:9200

  web:
    build: .
    command: python manage.py runserver 127.0.0.1:8000
    volumes:
    - .:/code
    ports:
    - "8000:8000"
    depends_on:
    - postgres-db
    - elasticsearch-db
