version: '3.4'  
services:
  web:
    build:
      # I'm not sure what this is doing,
      # but it will not run without it
      context: .
      dockerfile: ./Dockerfile
      network: host
    network_mode: host
    command: bash -c "python manage.py migrate && passenger start"
    # Inlcude environment file so don't have to
    # enter the container to modify variables
    env_file:
    - cbeImageDB/.env
    environment:
    - DB_HOST=localhost
    - ELASTIC_HOST=localhost
    - MEDIA_ROOT=/home/app/webapp/files
    - STATIC_ROOT=/home/app/webapp/static
    volumes:
    - "${MOUNT_MEDIA_ROOT}:/home/app/webapp/files"
    ports:
    - "80:80"
    depends_on:
    - postgres-db
    - elasticsearch-db
