version: '3.4'

services:

  postgres-db:
    image: postgres:11.6-alpine
    # restart: always (?)
    environment:
    - POSTGRES_PASSWORD=cbe_password
    - POSTGRES_USER=cbe_user
    - POSTGRES_DB=cbe_images
    ports:
    - 5432:5432

  elasticsearch-db:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.4.3
    environment: 
    - discovery.type=single-node
    ports:
    - 9200:9200

  web:
    build:
      # I'm not sure what this is doing,
      # but it will not run without it
      context: .
      dockerfile: ./Dockerfile
      network: host
    #image: cbe_web
    command: passenger start
    ports:
    - "80:8000"
    depends_on:
    - postgres-db
    - elasticsearch-db
