version: '3.4' 
# There are differences for mac computers, because docker cannot use the host
# network on a mac, the differences are documented below
services:
  web:
    build:
      # I'm not sure what this is doing,
      # but it will not run without it
      context: .
      dockerfile: ./Dockerfile
      network: host
    network_mode: host  # comment this out for use on mac
    # Change localhost to postgres-db here for mac
    command: bash -c "./wait-for-it.sh localhost:5432 -- python manage.py migrate && passenger start"
    # Inlcude environment file so don't have to
    # enter the container to modify variables
    env_file:
    - cbeImageDB/.env
    environment:
    - DB_HOST=localhost # postgres-db #for mac, localhost cbe
    - ELASTIC_HOST=localhost # elasticsearch-db #for mac, localhost cbe
    - MEDIA_ROOT=/home/app/webapp/files
    - STATIC_ROOT=/home/app/webapp/static
    volumes:
    - "${MOUNT_MEDIA_ROOT}:/home/app/webapp/files"
    ports:
    - "80:80"  # 8000 for mac, 80 for cbe
    depends_on:
    - postgres-db
    - elasticsearch-db
