version: '3.4'  
services:
  web:
    build:
      # I'm not sure what this is doing,
      # but it will not run without it
      context: .
      dockerfile: ./Dockerfile
      network: host
    #network_mode: host
    command: passenger start
    # This may need to change, but make 
    # sure it's not set to localhost
    environment:
    - DB_HOST=postgres-db
    - ELASTICSEARCH_HOST=elasticsearch-db
    - MEDIA_ROOT=/home/app/webapp/files
    - STATIC_ROOT=/home/app/webapp/static
    ports:
    - "80:8000"
    depends_on:
    - postgres-db
    - elasticsearch-db
