# Generated by Django 2.2.2 on 2020-01-28 21:16

import datetime
from django.db import migrations, models
import django.db.models.deletion
import easy_thumbnails.fields
import images.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Experiment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='GrowthSubstratum',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_taken', models.DateField(default=datetime.date.today, verbose_name='Date taken')),
                ('release_date', models.DateField(default=datetime.date.today, verbose_name="Can't be used before")),
                ('date_uploaded', models.DateField(default=datetime.date.today, verbose_name='Date uploaded')),
                ('document', models.ImageField(upload_to=images.models.imager_directory_path)),
                ('brief_description', models.CharField(max_length=1000)),
                ('path_to_raw_data', models.CharField(blank=True, max_length=500, null=True)),
                ('medium_thumb', easy_thumbnails.fields.ThumbnailerImageField(upload_to=images.models.medium_thumb_directory_path)),
                ('large_thumb', easy_thumbnails.fields.ThumbnailerImageField(upload_to=images.models.large_thumb_directory_path)),
            ],
        ),
        migrations.CreateModel(
            name='Imager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Lab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Microscope',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='MicroscopeSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='ObjectiveMedium',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Organism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=1000)),
                ('ncbi_id', models.CharField(max_length=100)),
                ('storid', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='Vessel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
            ],
        ),
        migrations.CreateModel(
            name='ProtectOrganism',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Experiment')),
                ('organism', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Organism')),
            ],
        ),
        migrations.CreateModel(
            name='ProtectLab',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('experiment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.Experiment')),
                ('lab', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Lab')),
            ],
        ),
        migrations.AddIndex(
            model_name='organism',
            index=models.Index(fields=['name'], name='images_orga_name_49cfc6_idx'),
        ),
        migrations.AddField(
            model_name='microscopesettings',
            name='medium',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.ObjectiveMedium'),
        ),
        migrations.AddField(
            model_name='microscopesettings',
            name='microscope',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Microscope'),
        ),
        migrations.AddField(
            model_name='image',
            name='experiment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Experiment'),
        ),
        migrations.AddField(
            model_name='image',
            name='imager',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Imager'),
        ),
        migrations.AddField(
            model_name='image',
            name='microscope_setting',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.MicroscopeSettings'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='lab',
            field=models.ManyToManyField(through='images.ProtectLab', to='images.Lab'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='organism',
            field=models.ManyToManyField(through='images.ProtectOrganism', to='images.Organism'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Project'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='substratum',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.GrowthSubstratum'),
        ),
        migrations.AddField(
            model_name='experiment',
            name='vessel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='images.Vessel'),
        ),
    ]
