# Generated by Django 2.2.2 on 2020-05-06 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organism',
            name='storid',
        ),
    ]
